jobs:
  include:
    - stage: test
      language: go
      go:
        - 1.12.x
        - 1.13.x
      sudo: false
      install:
        - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1
      script:
        - export PATH=$PATH:$HOME/gopath/bin
        - make all
    - stage: test
      language: node_js
      node_js:
        - "node"
      install:
        - npm install -g truffle
      script:
        - cd cmd/ethatomicswap/contract/src
        - truffle test
