jobs:
  include:
    - stage: test
      language: go
      go:
        - 1.9.x
        - 1.10.x
      sudo: false
      install:
        - go get -v github.com/alecthomas/gometalinter
        - gometalinter --install
      script:
        - export PATH=$PATH:$HOME/gopath/bin
        - make all
    - stage: test
      language: node_js
      node_js:
        - "node"
      install:
        - npm install -g truffle
      script:
        - cd cmd/ethatomicswap/contract/src
        - truffle test
